[package]
name = "glopy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globset = "0.4.9"
structopt = "0.3.26"
walkdir = "2.3.2"
